// Copyright 2020 De Staat der Nederlanden, Ministerie van Volksgezondheid, Welzijn en Sport.
// Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2
// SPDX-License-Identifier: EUPL-1.2

using NL.Rijksoverheid.CoronaCheck.BackEnd.Issuer.Services.Attributes;

namespace NL.Rijksoverheid.CoronaCheck.BackEnd.Issuer.Services.ProofOfTest
{
    public interface IProofOfTestService
    {
        /// <summary>
        ///     Signs the given proofOfTestAttributes and returns the signature wrapped as base64 encoded string
        /// </summary>
        /// <param name="proofOfTestAttributes">Attributes supported by the PoT service, see type</param>
        /// <param name="nonce">Nonce bytes in b64 format</param>
        /// <param name="commitments">Commitments generated by crypto library on the client as a json object</param>
        /// <param name="nameKeySet">Name of the keyset to load from the config for the crypto operations</param>
        /// <returns>ISM as JSON string</returns>
        (string, ProofOfTestAttributes) GetProofOfTest(ProofOfTestAttributes proofOfTestAttributes, string nonce, string commitments, string nameKeySet);

        /// <summary>
        ///     Generates a nonce and returns the value as a base64 string
        /// </summary>
        /// <returns></returns>
        string GenerateNonce(string keyName);

        /// <summary>
        ///     Generates a static QR for the given attributes
        /// </summary>
        /// <param name="proofOfTestAttributes">Attributes supported by the PoT service, see type</param>
        /// <param name="nameKeySet">Name of the keyset to load from the config for the crypto operations</param>
        /// <returns>Base64 string containing the QR as a PNG</returns>
        (string, ProofOfTestAttributes) GetStaticProofQr(ProofOfTestAttributes proofOfTestAttributes, string nameKeySet);
    }
}
